# Custom Language File for Launcher Customizer

[ejs.app]
title = "Create Academy Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/fairy-code/CreateAcademyLauncher2"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/fairy-code/CreateAcademyLauncher2"
supportLink = "https://github.com/fairy-code/CreateAcademyLauncher2/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO CREATE ACADEMY"
welcomeDescription = "You are using the Create Academy Launcher, this launcher was made by Fairy jeux. A fork of the launcher HeliosLauncher. So have a nice play in Create Academy!"
welcomeDescCTA = "You are just a few clicks away from Create Academy."
